### PR TITLE
On content size change prop is not being ran

### PR DESCRIPTION
**Pull request by chenop**
#3 

Support onContentSizeChange prop

### CODE REVIEW

**Review by mak12 — APPROVED** [review]

**Comment by chenop** [comment]
Thanks for approving this PR - I dont see the changes on the master - why is that?

**Comment by chenop** [comment]
Hi, Still dont see this on master, any idea?

**Comment by mak12** [comment]
Sorry was away, will merge these changes today.

**Comment by ashranhaider** [comment]
Kr de bhosri wale

**Pull request merged**
